# Описание файла конфигурации диалога
header: |-
  RsNPC - файл конфигурации диалога
  Предупреждение! Убедитесь, что вы освоили синтаксис YAML перед редактированием этого файла!
footer: |-
  Вы достигли конца файла конфигурации

defaultPage: "Страница, открываемая по умолчанию, укажите ключ на страницах ниже"
pages: |-
  формат страницы:
  - key: "1" # ключ страницы
    title: "Представление диалога" # заголовок страницы
    content: "Это демонстрационный диалог" # содержание страницы
    buttons: # кнопки
      - text: "закрыть" # отображаемое имя кнопки
        action: "закрыть" # оставьте это пустым, чтобы по умолчанию закрыть диалог
        cmd: # выполнение команды
          - "me привет" # разрешения игрока на выполнение команд
          - "say привет @p&op" # разрешение op на выполнение команд
          - "tell @p это тестовая команда&con" # привилегии консоли для выполнения команд
      - text: "следующая страница" # отображаемое имя кнопки
        go: "2" # перейти на другие страницы и заполните ключ других страниц
