# Описание файла конфигурации NPC
header: |-
  RsNPC - файл конфигурации NPC
  Предупреждение! Пожалуйста, убедитесь, что вы освоили синтаксис YAML перед редактированием этого файла!
footer: |-
  Вы достигли конца файла конфигурации

ConfigVersion: |-
  Номер версии файла конфигурации ПРЕДУПРЕЖДЕНИЕ! Не пытайтесь изменить эту конфигурацию, если точно не знаете, что делаете!

name: "Отображаемое имя NPC (над головой)"
nameTagAlwaysVisible: |-
  Видимо ли отображаемое имя NPC (над головой) всегда
  true - всегда видимо
  false - Видимо только тогда, когда игрок указывает на NPC
position: "Координаты NPC"
hand-item: "Идентификатор предмета в руке, например, 267:0, не будет отображаться, если пусто"
head-item: "Идентификатор предмета головной брони, например, 298:0, не будет отображаться, если пусто"
chestplate-item: "Идентификатор предмета брони нагрудника, например, 299:0, не будет отображаться, если пусто"
leggings-item: "Идентификатор предмета брони поножей, например, 300:0, не будет отображаться, если пусто"
boots-item: "Идентификатор предмета обуви, например, 301:0, не будет отображаться, если пусто"
skin: "Имя используемого скина"
entity-networkid: |-
  Идентификатор сети сущности, используемый при отправке пакета игроку
  Для введения идентификатора сущности обратитесь по ссылке: https://minecraft.fandom.com/wiki/Java_Edition_data_values/Pre-flattening/Entity_IDs
  Если нет особых требований, установите его на -1, чтобы использовать фиктивную сущность игрока
entity-size: "размер сущности"
look-at-player: "смотреть ли на игрока"
emotions.enable: "включены ли эмоции у NPC"
emotions.emoteid: |-
  Известные идентификаторы эмоций: https://github.com/lt-name/GetEmoteID/blob/master/README.md
  Обратите внимание! Эта конфигурация имеет тип Список!
  формат:
   - "ID1"
   - "ID2"
emotions.interval: "Интервал для воспроизведения эмоций NPC. Единица измерения: секунда"
projectile-triggering: "Разрешено ли снарядам, таким как стрелы, снежки и т. д., вызывать"
commands: |-
  Нажмите на NPC для выполнения команды
  Обратите внимание! Эта конфигурация имеет тип Список!
  формат:
   - "Команда1&Разрешения"
   - "Команда2&Разрешения"
  Перед & находится команда, а после - разрешение. Разрешение не указывает на стандартное разрешение игрока.
  &con выполнять команды с правами консоли
  &op Выполнить команды с правами оператора
  Например:
   - "give @p 260 1&con"
   - "say @p Привет&con"
messages: |-
  Нажмите на сообщение, отправленное NPC
  Обратите внимание! Эта конфигурация имеет тип Список!
  формат:
   - "сообщение1"
   - "сообщение2"
  Например:
   - "%npcName%: @p Привет"
   - "Посылаю вам яблоко!"
movement-speed: "скорость движения NPC"
route: "Список путей. Пожалуйста, используйте команду для добавления!"
enable-assisted-pathfinding: |-
  помощь в поиске пути
  После включения NPC автоматически перемещается вокруг препятствий к целевой точке (рекомендуется при изменении местности)
  Не включайте NPC, игнорирующего препятствия, и перемещайтесь прямо к целевой точке (сэкономит производительность, если местность не изменится)
whirling: |-
  Угол поворота NPC установлен на отрицательное число, чтобы развернуть поворот
  может быть использован для вращения скинов
  При включении этой опции автоматически отключается движение NPC
dialog.enable: "включить ли диалог"
dialog.dialog: "Имя файла конфигурации диалога"

CustomEntity: |-
  Связанная с настраиваемой сущностью конфигурация
  Внимание! Эта функция должна использоваться с текстурным пакетом!
  Внимание! После регистрации настраиваемой сущности игроку необходимо перезайти на сервер, чтобы она отобразилась. Рекомендуется изменять эту конфигурацию после закрытия сервера!
CustomEntity.enable: "включить ли настраиваемые сущности"
CustomEntity.identifier: "Идентификатор настраиваемой сущности (установленный в ресурсном пакете)"
CustomEntity.skinId: "Идентификатор скина сущности (вариант), обычно по умолчанию 0"

CustomCollisionSize: |-
  настраиваемый размер столкновения
  Если NPC использует особую форму скина, вы можете настроить эту конфигурацию
  Позволяет игрокам лучше кликать по сущностям NPC в игре
CustomCollisionSize.enable: "включить ли настраиваемый размер столкновения"