name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.4.4-PNX"
api:
  - "2.0.0"
authors: ["若水", "LT_Name"]
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

permissions:
  RsNPC.admin:
    default: op
    description: "Plugin main command"
  RsNPC.admin.create:
    default: op
    description: "Create NPC command"
  RsNPC.admin.delete:
    default: op
    description: "Delete NPC command"
  RsNPC.admin.reload:
    default: op
    description: "Reload config command"
  RsNPC.admin.addroute:
    default: op
    description: "Add NPC movement path command"