name: RsNPC
main: com.smallaswater.npc.RsNPC
version: "2.3.1-PM1E-SNAPSHOT"
api: ["Nukkit-PM1E"]
authors: ["若水", "LT_Name"]
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

permissions:
  RsNPC.admin:
    default: op
    description: "RsNPC插件主命令"