# dialog 配置文件描述
header: |-
  RsNPC - dialog配置文件
  警告！编辑此文件前请确认您已掌握YAML语法！
  您可以从这里学习YAML
  https://www.runoob.com/w3cnote/yaml-intro.html
footer: |-
  你已经到达配置文件的底部啦

defaultPage: "默认打开的dialog，填写下方pages中的key"
pages: |- 
  dialog 格式：
  - key: "1" #dialog的key
    title: "演示dialog" #dialog标题
    content: "这是一个演示dialog" #dialog内容
    buttons: #按钮
      - text: "关闭" #按钮显示名称
        action: "close" #此项留空默认关闭dialog
        cmd: #执行命令
          - "me hello" #玩家权限执行命令
          - "say hello @p&op" #op权限执行命令
          - "tell @p 这是一个测试命令&con" #控制台权限执行命令
      - text: "下一页" #按钮显示名称
        go: "2" #前往其他dialog 填写其他dialog的key